---
# This playbook handles tasks that Terraform might not handle efficiently
# Like uploading files, waiting for ACM validation, or creating CloudFront invalidations

- name: Post-Terraform Tasks
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    aws_region: ap-south-1
    s3_bucket: "{{ s3_bucket_name | default('vinod.digital') }}"
    distribution_id: "{{ cloudfront_distribution_id }}"
    build_dir: "{{ build_directory | default('../dist') }}"
    
  tasks:
    - name: Wait for ACM certificate validation
      command: >
        aws acm describe-certificate 
        --certificate-arn {{ acm_certificate_arn }} 
        --region us-east-1
      register: cert_status
      until: "'ValidationMethod": "DNS"' in cert_status.stdout and "'Status": "ISSUED"' in cert_status.stdout
      retries: 60
      delay: 30
      changed_when: false
      when: wait_for_acm_validation | default(false) | bool
      
    - name: Sync build files to S3
      amazon.aws.s3_sync:
        bucket: "{{ s3_bucket }}"
        file_root: "{{ build_dir }}"
        delete: true
        permission: private
        region: "{{ aws_region }}"
      when: upload_build | default(false) | bool
      
    - name: Create CloudFront invalidation
      command: >
        aws cloudfront create-invalidation 
        --distribution-id {{ distribution_id }} 
        --paths "/*"
      when: create_invalidation | default(false) | bool
