name: Deploy React App to AWS

on:
  push:
    branches:
      - main # Development branch
      - production # Production branch
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        type: choice
        required: true
        default: "development"
        options:
          - development
          - production

permissions:
  id-token: write # Required for OIDC authentication
  contents: read # Required to check out the repository

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    # Set environment based on branch or manual input
    env:
      ENVIRONMENT: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || (github.ref == 'refs/heads/production' && 'production' || 'development') }}
      AWS_REGION: ap-south-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build React app
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        run: |
          echo "Deploying to S3 bucket: $S3_BUCKET"
          aws s3 sync ./dist s3://$S3_BUCKET/ --delete

      - name: Invalidate CloudFront cache
        run: |
          echo "Creating CloudFront invalidation for distribution: $DISTRIBUTION_ID"
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
